services:
  neo4j:
    image: neo4j:2025.09
    volumes:
      - neo4j_data:/data
    environment:
      - NEO4J_AUTH=neo4j/your_password
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always

volumes:
  neo4j_data:
